# Generated by Django 3.0 on 2021-11-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
